apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfodr5529-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfodr5529-tenant-component
    app.kubernetes.io/part-of: loadfodr5529-tenant-app
  name: loadfodr5529-tenant-component
  namespace: loadfodr5529-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadfodr5529-tenant-component
    weight: null
status: {}
